# Generated by Django 4.1.1 on 2022-09-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightdata',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='carbon_emissions',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flightdata',
            name='origin',
        ),
        migrations.AddField(
            model_name='flightdata',
            name='time',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
