# Generated by Django 4.1.1 on 2022-09-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_flightdata_arrival_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='flightdata',
            name='carbon',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='lat',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='long',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='true_track',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='flightdata',
            name='velocity',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='callsign',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='flightdata',
            name='time',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
